version: '3.4'

services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test12345
      MYSQL_DATABASE: authtestdb
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
    datafiles: