// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SciMaterials.UrlsService.Api.Data;

#nullable disable

namespace SciMaterials.UrlsService.Api.Migrations
{
    [DbContext(typeof(UrlsStorageContext))]
    [Migration("20230618145617_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SciMaterials.UrlsService.Api.Data.UrlEntity", b =>
                {
                    b.Property<string>("ShortenedRouteSegment")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessCount")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAccess")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShortenedRouteSegment");

                    b.ToTable("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
